# Merging mit Geodaten

In [13]:
import pandas as pd

sess = pd.read_csv("sessions.csv")

loc = pd.read_csv("world_cities.csv")
loc = loc.fillna('')
loc.head()

  country state county                 name       lat      lng
0      AD                              Vila  42.53176  1.56654
1      AD                         El Tarter  42.57952  1.65362
2      AD               Sant Julià de Lòria  42.46372  1.49129
3      AD                    Pas de la Casa  42.54277  1.73361
4      AD                            Ordino  42.55623  1.53319

In [4]:
sess

,sess_ctry,sess_loc,datum,sug_platform,landing_uri,session_duration,pages_per_sess,jump_offs,sess_cart_add,sess_co,sess_co_done,sessions
0,Germany,Nuremberg,2024-10-01,direct,https://www.whiskyquartier.de/pages/datenschutz,368.000000,5.000000,0,0,0,0,1
1,Germany,Munich,2024-10-01,direct,https://www.whiskyquartier.de/products/kavalan...,237.000000,7.000000,0,1,1,0,1
2,United Kingdom,London,2024-10-01,direct,https://www.whiskyquartier.de/password,0.000000,1.000000,1,0,0,0,1
3,Germany,Hausach,2024-10-01,direct,https://7bb991-55.myshopify.com/,0.000000,1.000000,1,0,0,0,1
4,Germany,Burgthann,2024-10-01,direct,https://7bb991-55.myshopify.com/,327.555556,1.888889,7,0,0,0,9
...,...,...,...,...,...,...,...,...,...,...,...,...
2205,Germany,Bochum,2025-08-01,direct,https://www.whiskyquartier.de/account/subscrib...,42.000000,3.000000,0,0,0,0,1
2206,Germany,Altfraunhofen,2025-08-01,meta,https://www.whiskyquartier.de/?utm_source=FB+W...,102.000000,2.000000,0,0,0,0,1
2207,Portugal,Guimarães,2025-08-01,direct,https://www.whiskyquartier.de/products/kavalan...,0.000000,1.000000,1,0,0,0,1
2208,Germany,Leipzig,2025-08-01,meta,https://www.whiskyquartier.de/?utm_source=FB+W...,54.000000,3.000000,0,0,0,0,1
2209,Germany,Berlin,2025-08-01,meta,https://www.whiskyquartier.de/?utm_source=FB+W...,0.000000,1.000000,1,0,0,0,1

In [6]:
def get_geo(name:str) -> dict:
    tmp = loc[loc['name'] == name][['lat', 'lng']]
    return {'lat': tmp['lat'], 'lng': tmp['lng'] }

In [7]:
print(get_geo("Leipzig"))

{'lat': 32594    51.33962
Name: lat, dtype: float64, 'lng': 32594    12.37129
Name: lng, dtype: float64}

In [9]:
sess['land_pg'] = sess['landing_uri'].str[0:65]
sess.columns

Index(['sess_ctry', 'sess_loc', 'datum', 'sug_platform', 'landing_uri',
       'session_duration', 'pages_per_sess', 'jump_offs', 'sess_cart_add',
       'sess_co', 'sess_co_done', 'sessions', 'land_pg'],
      dtype='object')

In [10]:
sess_clean = sess[['sess_ctry', 'sess_loc', 'datum', 'sug_platform',
       'session_duration', 'pages_per_sess', 'jump_offs', 'sess_cart_add',
       'sess_co', 'sess_co_done', 'sessions', 'land_pg']]

In [12]:
sess_clean.to_csv("sess_clean", index=False)
sess_clean.head()

,sess_ctry,sess_loc,datum,sug_platform,session_duration,pages_per_sess,jump_offs,sess_cart_add,sess_co,sess_co_done,sessions,land_pg
0,Germany,Nuremberg,2024-10-01,direct,368.000000,5.000000,0,0,0,0,1,https://www.whiskyquartier.de/pages/datenschutz
1,Germany,Munich,2024-10-01,direct,237.000000,7.000000,0,1,1,0,1,https://www.whiskyquartier.de/products/kavalan...
2,United Kingdom,London,2024-10-01,direct,0.000000,1.000000,1,0,0,0,1,https://www.whiskyquartier.de/password
3,Germany,Hausach,2024-10-01,direct,0.000000,1.000000,1,0,0,0,1,https://7bb991-55.myshopify.com/
4,Germany,Burgthann,2024-10-01,direct,327.555556,1.888889,7,0,0,0,9,https://7bb991-55.myshopify.com/

In [17]:
loc.to_csv("loc_clean.csv", index=False)
loc["name"].str.len().max()

np.int64(65)